### ISSUE TITLE
Mobile View needs to be implemented

### ISSUE THREAD

**Issue by karnie6** [karnie6/helpdesk-nft-armory#24]

**Comment by karnie6** [comment]
or atleast a screen that says we dont support mobile yet (please visit this on Desktop)

**Comment by patenish** [comment]
used this approach: 

https://renatello.com/vue-js-detect-mobile/
https://www.npmjs.com/package/vue-mobile-detection

**Comment by patenish** [comment]
addressed this piece in the following merged + closed PR: https://github.com/karnie6/helpdesk-nft-armory/pull/65
